### ISSUE TITLE
Too many images generated when animating.

### ISSUE THREAD

**Issue by cjgammon** [cjgammon/SnapSVG-Animator#20]
When animating Bitmap with Fill, images are generated for each frame even if the image source image does not change.

**Comment by cjgammon** [comment]
I'm still seeing this as an issue, i'll e-mail an example .fla that shows it.

**Comment by cjgammon** [comment]
This seemed to be fixed in the latest version. @kundugoutam can you confirm?

**Comment by kundugoutam** [comment]
The initial fix for this problem that I had done was to fix the re-use of image issue ie if an image is being used in multiple bitmap fills, only one image file will be generated in the “images” folder.

However, it will still generate multiple shape assets and generate “Place” and “Remove” commands for two shapes with bitmap fills and different scaling/rotation.This is a technical limitation in FlashPro CPSDK. You will notice similar behaviour in SWF as well.
