### ISSUE TITLE
A version for Flash CS6 ?

### ISSUE THREAD

**Issue by akkolad** [cjgammon/SnapSVG-Animator#52]
Hi,
it seems that to be an excellent product you've made, but I can't install it because I use Flash CS6.
I've tried with the Extension Manager but it failed (because of the manifest.xml).
Will you code a version for Flash CS6 ?

Thanks.

**Comment by kundugoutam** [comment]
Thanks for your interest. SnapSVG-Animator plugin is created using Custom Platform Support Development Kit (https://helpx.adobe.com/flash/using/custom-platform-support-api-reference.html) which is supported in Flash CC 14.1 onwards. So, this will not work in Flash CS6.
