### ISSUE TITLE
Won't install on Animate CC

### ISSUE THREAD

**Issue by Bob-E** [cjgammon/SnapSVG-Animator#62]
Says I need Flash version 12 or later

**Comment by tmsunil** [comment]
Are you using the latest version of Adobe Animate CC?

Have you tried installing it using the "Manage Extensions Utility" mentioned in the page https://helpx.adobe.com/animate/kb/install-animate-extensions.html?

**Comment by Bob-E** [comment]
Thanks tmsunil, this issue is resolved. My issue was **Installation failed, escalated privileges required**, so I uninstalled from the add-on page, waited a few minutes, rebooted my machine, and started the process over again. This time CC alerted me to sign in as administrator, and the add-on was installed successfully.
