### ISSUE TITLE
Export to a selector

### ISSUE THREAD

**Issue by impartdan** [cjgammon/SnapSVG-Animator#63]
Is it possible to export so that your svg is inserted into a DOM node?

**Comment by cjgammon** [comment]
You can inject the SVG into an element.  See the snippet below, where container is your DOM node.

```javascript
comp = new SVGAnim(json, width,height,fps);  
container.appendChild(comp.s.node); 
```

I've added a little documentation about the [SnapSVGAnimator API](https://github.com/cjgammon/SnapSVG-Animator/wiki/API).  You can see `SVGAnim` has an `s` property which is the snap surface exposing the `node` property from Snap's API.  You can read about [Snap's API](http://snapsvg.io/docs/) on it's website.
