### ISSUE TITLE
The zxp file is corrupt

### ISSUE THREAD

**Issue by sahibvirk** [cjgammon/SnapSVG-Animator#64]
I have checked with 3 different software for installing zxp files. The latest one that you have uploaded is corrupt and is not unpacking by any software properly.

Yes the software i tried was "Adobe extensions manager"..

Please help me

My one whole day was wasted trying to make it work

Seriously it is not unpacking 

Just try yourself

**Comment by cjgammon** [comment]
Sorry, I'll revert to the previous ZXP there must have been a signing error.  In the future if you would install through the CC addons portal the one up there should work fine.

https://creative.adobe.com/addons/products/12329#.Vv2AXxMrIUE

**Comment by cjgammon** [comment]
I have reverted to an older ZXP that should work.  Also adobe extension manager is no longer being supported by Adobe (https://www.adobeexchange.com/resources/27).

**Comment by sahibvirk** [comment]
Sorry friend.
But I think there's something still wron. The lastzxp I downloaded was 11MB.
But this new one is only 520KB. This is not installing eigther.
It says Error Code -180 and some problem with the xml file.

I think the new zxp did not upload properly.

**Comment by cjgammon** [comment]
I'm sorry you're still having problems, I was able to install this zxp and publish with it after downloading this .zxp directly from github. The file size difference is expected as this is an version before some major changes were made.

It sounds like there's either a problem with the method you're using to install it or there's some other more specific problem.

As I mentioned make sure you are not using the Extension Manager application.  I would highly recommend installing through the CC addons portal as this is the recommended way to do it now.  

Alternatively here's a command line tool to do it:
https://www.adobeexchange.com/resources/28

If you continue to have problems please let me know what method you use to install it and what version of flash you are running along with the error/outcome.
