### ISSUE TITLE
EventListeners

### ISSUE THREAD

**Issue by juanitoddd** [cjgammon/SnapSVG-Animator#65]
Hello Guys !!

CJ, kundugoutam, tmsunil, Mad work on this plugin, Its so cool :)

Was wondering if there is a way to attach Event Listeners on the Shapes/MC´s and objects in general,
Either inside Flash or outside using javascript to reference the <g>

Any ideas on that ? Thanks in advance

**Comment by cjgammon** [comment]
Hi!
Scripting is relatively new and not yet submitted to the addons portal but it is supported in the 'dev' branch.  You can see a preview of how scripting works using the Snap.svg javascript API in this youtube video: 

https://www.youtube.com/watch?v=buR7XhKCKlM
