### ISSUE TITLE
Move SVG

### ISSUE THREAD

**Issue by qpl88** [cjgammon/SnapSVG-Animator#66]
Hi,

Sorry if this is a simple question but I've been trying to figure out how I can specify where the svg will be appended to, I've searched a lot online with no luck and I'm newish to javascript, so I couldn't find where to specify this. I want to render 4 svgs I've created through Animate CC into different tabbed sections.

What is the best way to do this, any help would be greatly appreciated.

Thanks

**Comment by cjgammon** [comment]
Hi, See the response in #63

**Comment by qpl88** [comment]
Thank you!
