### ISSUE TITLE
Start, Stop and reset

### ISSUE THREAD

**Issue by qpl88** [cjgammon/SnapSVG-Animator#67]
Hi,

I've got my compositions playing without a problem, and I've done some manual starting and stopping. I was wondering if there was a cleaner way of doing a start, stop and reset to frame 1? Right now I have the following which starts and stops and sets the loop to 1.

function playComp(compToAnimate) {
    compToAnimate.movieclip.loops = true;
    compToAnimate.play();
    setTimeout(function () {
        compToAnimate.movieclip.loops = false;
        $('.tab.active .play-button').addClass('visible');
    }, 3000);
}
I have my compositions in separate tabs and I use the above function in my callbacks. But if I switch tabs and switch back before the animation has finished, it is still running.

I'd like to have the animation play on an active tab once and when it's finished give the option to play it again via a button I've already created, but if the tab is switched before it has finished playing, to stop and reset the inactive tabs svg.

I hope that makes sense, thank you in advance and for this great plugin.

**Comment by cjgammon** [comment]
What you are asking for is full scripting support. See #51 . This is not available on the public release yet, but it is working in `dev` branch. See if you can get the zxp on that branch installed through the [ExManCmd command line tool](https://www.adobeexchange.com/resources/28).  It's not as straight forward so you may have to mess with it some, but if you get it working scripting, such as `gotoAndStop(1)` should work. There's a video showing how scripting works with the plugin [in the wiki](https://github.com/cjgammon/SnapSVG-Animator/wiki/Getting-Started).
