### ISSUE TITLE
How can I stop the animation from automatically playing, and turn off looping?

### ISSUE THREAD

**Issue by Jamie452** [cjgammon/SnapSVG-Animator#70]
I've just exported using the plugin and can't figure out how to stop the animation from automatically playing and looping?

The best I've been able to do is to call `comp.mc.stop();` straight after `SVGAnim` gets initialised.

**Comment by cjgammon** [comment]
You should be able to create a keyframe for the first frame on a new layer in the timeline of the movieclip and call `this.stop();`  in the actions panel.

For looping the following should work:
`comp.mc.loops = false;`

The method you're using above should work as well, but it seems to stop before rendering which is a bug.

**Comment by cjgammon** [comment]
This is fixed on `dev` if you update the generated files with the files in the following commit, it should work as expected

https://github.com/cjgammon/SnapSVG-Animator/commit/c7949f8e6d5a67aa2bd3c24d674523fa82ee3c8b
