### ISSUE TITLE
gotoAndPlay on a Nested Timeline Replicates Movie Clip

### ISSUE THREAD

**Issue by blastframe** [cjgammon/SnapSVG-Animator#77]
Anyone know what I'm doing wrong or if this is a bug?

I have created an SVG animation using SnapSVG-Animator.

I'm trying to get it to play the nested timeline in segments (frames 2 to 246), but it's duplicating the movie clip instance (to see what I mean, press the left and right arrows several times in a row):

http://blastframe.com/snap/

Within the plane Movie Clip, I have an actions layer with a stop on the first frame and two frames with labels: "left" and "right."

**Comment by cjgammon** [comment]
I pushed some changes to the `dev` branch that seem to resolve this issue.  You should be able to swap out the SVGAnimator.js file in your project with the one in `dev` and get the correct behavior.  Let me know if this works.

**Comment by blastframe** [comment]
Hi @cjgammon ,
That fixed it! 👍  I have a new issue that I'll create a new issue for...thanks!

**Comment by blastframe** [comment]
Hi @cjgammon ! When with this fix be in the .zxp? My team is looking to use SnapSVG-Animator and this behavior. Thanks!

**Comment by cjgammon** [comment]
I added a new .zxp to the `dev` branch.

**Comment by blastframe** [comment]
Thank you for doing that. When will this be in the Master branch?
