### ISSUE TITLE
Navigating a Movie Clip Timeline with Actions

### ISSUE THREAD

**Issue by blastframe** [cjgammon/SnapSVG-Animator#78]
When I put "this.gotoAndStop(0)" in the .fla timeline within a Movie Clip, SnapSVG-Animator ignores it. "this.stop()" works, however. Is this an issue of Javascript scope, perhaps? How can I get the animation reset to a default location (or loop) after the timeline animation has completed? Thank you!

**Comment by cjgammon** [comment]
See if `this.gotoAndStop(1)` works.

**Comment by blastframe** [comment]
That does.
