### ISSUE TITLE
Cannot export certain graphics as svg animation.

### ISSUE THREAD

**Issue by fashaikh** [cjgammon/SnapSVG-Animator#81]
Cant figure out how to translate this error to changes I need to make it work.

Publishing begins for document with GUID: C457B30A-A9EA-4FE6-B468-334F8F57075B
Creating output file : C:\Users\fashaikh\AppData\Local\Temp\SnapSVGAnimator\Untitled41.html

Warnings generated while copying/importing in Untitled-1:
* Blend Modes(Layer) is not supported in SnapSVGAnimator document, and has been converted to Normal in an instance of Movieclip <Path>.
* ColorEffect is not supported in SnapSVGAnimator document, and has been removed in an instance of Movieclip <Path>.

 The 'SymbolInstance.filters' JS API is not supported for SnapSVGAnimator.
 The 'SymbolInstance.filters' JS API is not supported for SnapSVGAnimator.
 The 'SymbolInstance.filters' JS API is not supported for SnapSVGAnimator.
![snapsvg](https://cloud.githubusercontent.com/assets/2650941/18068565/cc24d72c-6df6-11e6-89f3-4b7292f024bf.PNG)

**Comment by cjgammon** [comment]
It seems like you're trying to use an item that has a bunch of features, specifically filters not currently supported by SnapSVGAnimator, including Blend Modes and Color Effect.  Try removing these.

**Comment by fashaikh** [comment]
I imported the .fla file and tried to export that, and it only had 
showed this error

> The 'SymbolInstance.filters' JS API is not supported for SnapSVGAnimator.


For now, I went ahead with plain Javascript animation, since I could more or less achieve what I wanted by changing the classes of each item in the svg file. I'll close this bug for now.
