### ISSUE TITLE
Using SVG for Navigation :  Make cursor be a pointer

### ISSUE THREAD

**Issue by alexrumsey** [cjgammon/SnapSVG-Animator#83]
I am using SnapSVG-Animator for an animated navigation and I would like the "buttons" to have a pointer when hovered. I can't seem to figure out how to make this happen. I was going to target SVG groups with CSS but there aren't any id's or classes that I can target. 

It looks like it's possible from your video: https://youtu.be/buR7XhKCKlM

I was hoping you could share that project file and/or tell me how you did it.

Thanks.

**Comment by cjgammon** [comment]
inside a movieclip you can put the following code on the timeline:
```
this.el.attr({cursor: 'pointer'});
```

**Comment by alexrumsey** [comment]
Thank you!
