### ISSUE TITLE
Very simple stop() and play()

### ISSUE THREAD

**Issue by mbuckley1** [cjgammon/SnapSVG-Animator#86]
First of all this is a brilliant solution for what we want to do - unfortunately I can't seem to do any of the basics. I have a graphic on one layer in the flash file, motion tween a rotate over 50 frames (no frame scripts). Export the project and it animates and loops fine. Ultimately I'd like to move the playhead on a page scroll (back and forth etc.) but before that I've tried triggering stop() and play() by clicking external div elements. The stop() works but play doesn't, I've found the functions inside SnapSVGAnimator.min.js added some console messages and they all fire. If I add a frame script in the flash file, first frame this.stop() then if I call play() again the playhead advances one frame at a time... even tried adding movieclips dynamically from the library - I've tried all sorts of nonsense to no avail, I'm stumped - what am I missing?

`var comp;
var jsonfile = "Animator.json",
            fps = 24,
            width = 1015,
            height = 400,
            AJAX_req;

    AJAX_JSON_Req(jsonfile);

    function handle_AJAX_Complete() {
        if( AJAX_req.readyState == 4 && AJAX_req.status == 200 )
        {
            json = JSON.parse(AJAX_req.responseText);
             comp = new SVGAnim(
                           json,
                           width,
                           height,
                           fps
						   );
			}
    }

    function AJAX_JSON_Req( url )
    {
        AJAX_req = new XMLHttpRequest();
        AJAX_req.open("GET", url, true);
        AJAX_req.setRequestHeader("Content-type", "application/json");
        
        AJAX_req.onreadystatechange = handle_AJAX_Complete;
        AJAX_req.send();
    }

            `

`<div class="CLICKPLAY"> PLAY </div>
<div class="CLICKSTOP"> STOP </div>`

`$(".CLICKPLAY").click(function(){
comp.play();
});
			
	$(".CLICKSTOP").click(function(){
		comp.stop();
			});
			`

**Comment by cjgammon** [comment]
There was a bug around resuming on the root animation object.  This is fixed now on `dev`.  If you replace your SnapSVGAnimator.js file with the one on `dev` it should fix your problem.

**Comment by mbuckley1** [comment]
Brilliant! - Thank you ever so much!

**Comment by casillasluisn12** [comment]
Where do you replace it? on a Mac
