### ISSUE TITLE
Call functions within fash code from js.

### ISSUE THREAD

**Issue by RSBartesania** [cjgammon/SnapSVG-Animator#87]

**Comment by RSBartesania** [comment]
Hi, is it possible to call a function from external JS? For example. I create a function within flash:
function foo(){
console.log("foo");
}
I would like to call ir from the HTML file:
if( AJAX_req.readyState == 4 && AJAX_req.status == 200 )
        {
            json = JSON.parse(AJAX_req.responseText);
            comp = new SVGAnim(
                           json,
                           width,
                           height,
                           fps
                           );
            
            comp.mc.foo();
        }
}
This doesn't work...

Thanks!

**Comment by cjgammon** [comment]
This should work, but you'd have to define the function correctly on the object, 

```
this.foo = function () {

}
```
