### ISSUE TITLE
ID is not defined.

### ISSUE THREAD

**Issue by MaximilianLloyd** [cjgammon/SnapSVG-Animator#91]
No matter what I do I keep getting this issue. 
![capture](https://cloud.githubusercontent.com/assets/10583205/22038882/16cb1488-dcfd-11e6-86f2-019506a17325.PNG)
Wish I could use this tool but for now I am not capable. Help is needed urgently and would be greatly appreciated.

**Comment by MaximilianLloyd** [comment]
Here is the line that it is referring to.
![capture](https://cloud.githubusercontent.com/assets/10583205/22041894/fdfdbaa8-dd08-11e6-85a3-fda58fd51d29.PNG)

**Comment by cjgammon** [comment]
is it possible for you to share an example .fla and scripts generating this error?

**Comment by MaximilianLloyd** [comment]
I suspected the problem was my module bundler, browserify. When the libraries where not being imported with browserify it worked. Never got to the bottom of why it didn't work with browserify though.

**Comment by MaximilianLloyd** [comment]
@cjgammon It is happening again. Every time i try to include it using browserify i get the error shown above.
![capture1](https://cloud.githubusercontent.com/assets/10583205/22115988/5af37402-de6f-11e6-9a28-e5ab18c38fe4.PNG)

**Comment by MaximilianLloyd** [comment]
I have an Animation class which calls the SnapSVgAnimator. and it looks like this

```
import 'whatwg-fetch';
import config from 'components/config';

export default class Animation {
  constructor(name, width, height, container, callback, fps=30) {
    this.name      = name;
    this.width     = width;
    this.height    = height;
    this.container = container;
    this.fps       = fps;

    this.play = this.play.bind(this);

    let cachedAnimation = window.animationCache[name];
    if(!cachedAnimation) {
      fetch(`${config.basePath}/deps/animations/${name}.json`)
        .then(res => res.json())
        .then(instructions => {
          this.instructions = instructions;
          callback();
        });
    } else {
      this.instructions = cachedAnimation;
      callback();
    }
  }

  play() {
    this.comp = new SVGAnim(this.instructions, this.width, this.height, this.fps);
    this.container.appendChild(this.comp.s.node);
  }
}

```

**Comment by cjgammon** [comment]
If you inspect the generated SVG element does it have an ID?  also if you log out this.comp.s.id what does it return?  The id should be generated by Snap.svg.  Also, there may be some issues with Snap.svg and browserify.  https://github.com/adobe-webplatform/Snap.svg/issues/344

**Comment by MaximilianLloyd** [comment]
That is probably what is causing the problem. I'll try and see if I can find a work around for it.
