### ISSUE TITLE
SVG Animations causing massive jank on mobile

### ISSUE THREAD

**Issue by MaximilianLloyd** [cjgammon/SnapSVG-Animator#92]
I have 5 pages, only 1 of them currently have animations in (the one show in the gif). As you can see when i scroll there is massive jank. When i remove the animations the jank is gone. I have tried making SVGs absolute, but nothing has helped so far. I have also tested this on my ipad and gotten the same result. 
![jank](https://cloud.githubusercontent.com/assets/10583205/22185007/51619cbe-e0dd-11e6-839a-e16ceb4129a9.gif)

**Comment by MaximilianLloyd** [comment]
Also in chrome on android it stops playing when you are scrolling.

**Comment by MaximilianLloyd** [comment]
This is genuinely crippling.

**Comment by cjgammon** [comment]
SVG by its nature creates a lot of elements and DOM manipulation when animating which can be performance intensive particularly on mobile.  You'll definitely want to ensure things aren't animating when they're not in view, perhaps even stopping all of them while scrolling.  

If you're still having performance issues with SVG, you may also want to consider using the canvas exporter for your output. You're asking a lot of the browser renderer using this many animations in one mobile page while scrolling.

**Comment by MaximilianLloyd** [comment]
Hmm ok. Thank you for the help. I think I may just end up using GIFs on mobile due to widespread support.
